### ISSUE TITLE
这个是什么项目

### ISSUE THREAD

**Issue by daydayfree** [cuteio/cute-ObjectiveC-client#1]
饼饼...

**Comment by lisongx** [comment]
为什么close了！

**Comment by liluo** [comment]
你们不要在我的项目中来撒欢好吗!!!

**Comment by daydayfree** [comment]
试了试 github 的各项功能，都还能用。:smile:

**Comment by lisongx** [comment]
小诺好久不见

**Comment by daydayfree** [comment]
为社么占这么多坑，还不快快贴代码。

**Comment by lisongx** [comment]
对，你的大项目呢

**Comment by kkx** [comment]
:smile:

**Comment by liluo** [comment]
时间过得太匆匆

**Comment by lisongx** [comment]
我最近有个大项目 有人一起做吗

**Comment by kkx** [comment]
zuo!

**Comment by liluo** [comment]
多大啊? 西班牙的国际友人都要援助了

**Comment by lisongx** [comment]
绝对大 悄悄的

**Comment by lisongx** [comment]
前几天发现一个数据集 https://www.githubarchive.org/ log下了github的所有动作，我想做一个每周(或者每天）的新闻邮件，订阅的人可以看到[中国]地区开发者的最热门项目，最新热门项目 etc...
who's in?

**Comment by lisongx** [comment]
怎么都消失了

**Comment by bingwen** [comment]
粗线了

**Comment by bingwen** [comment]
有点意思啊，可以用来做数据分析

**Comment by lisongx** [comment]
@bingwen 
对，技术上第一步是聚合一个github中文用户的表

**Comment by lisongx** [comment]
然后就可以联合它那些数据用google bigquery查表了

**Comment by kkx** [comment]
http://stackoverflow.com/questions/7329978/how-to-list-all-github-users
looks like there is not a simple way to get a list of all github member, therefore more challenging would be extracting all chinese members.  A crawler might be the solution(ugly one).

by the way, take a look a http://www.pointer.io/, a similar newsletter application.
i think location could be an attribute for a more generic cause. something like projects recommendation according to language, location, funcionality, etc (some feature which should be implemented by github itself )

**Comment by lisongx** [comment]
@kkx 
你为什么还整英文

对于第一个，我想到的办法是，就从 https://www.githubarchive.org/ 下载下来2013 2014的所有log，从中很容易拿到期间发生过动态的github用户id，再用github的api获得地区，保存下来中文的，作为一个base来存。之后对每天发生的log过滤查出中国用户，然后对数据进行增量更新。

不知道这个newsletter。但是我觉得中文地区还是有可做的东西的，因为国内的项目、开发者离自己的距离也更近吧。any idea？

**Comment by daydayfree** [comment]
最后也是通过日志聚合，找到有价值的东西。但是这里有价值的东西是些什么东西？有什么特征呢？

**Comment by kkx** [comment]
@seansay  no chinese in work

**Comment by lisongx** [comment]
@daydayfree @kkx

一个简单的例子，就是

本周内，或者本月内
- 最主要的，也是最常见的。最热门的项目、新项目（这个日志中的star+watch事件按一定公式来衡量）
- 中文用户最关注的项目（不确定这个是否有意义……）
- 最活跃的中文用户（比较好玩？）

**Comment by lisongx** [comment]
落总贡献台服务器！

**Comment by liluo** [comment]
你就在 DAE 上弄, 完了让 taotao 允许你外网访问就成了. 或者, 你可以用 http://biz-dev.douban.com/ 这是一台单独的虚拟机, 2G 内存够你用了, 你问 taotao 要权限.
